apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: addressrs
spec:
 replicas: 2
 selector:
  matchLabels:
   app: java
 template:
  metadata:
   name: mypod
   labels:
    app: java
  spec:
   containers:
    - name: addresscont
      image: bhavaniprasan/addressimg:latest
